{
    "voice_id": "bVMeCyTHy58xNoL34h3p",
    "name": "Jeremy",
    "samples": null,
    "category": "premade",
    "fine_tuning": {
        "language": null,
        "is_allowed_to_fine_tune": false,
        "fine_tuning_requested": false,
        "finetuning_state": "not_started",
        "verification_attempts": null,
        "verification_failures": [],
        "verification_attempts_count": 0,
        "slice_ids": null,
        "manual_verification": null,
        "manual_verification_requested": false,
    },
    "labels": {
        "accent": "american-irish",
        "description": "excited",
        "age": "young",
        "gender": "male",
        "use case": "narration",
    },
    "description": null,
    "preview_url": "https://storage.googleapis.com/eleven-public-prod/premade/voices/bVMeCyTHy58xNoL34h3p/66c47d58-26fd-4b30-8a06-07952116a72c.mp3",
    "available_for_tiers": [],
    "settings": null,
    "sharing": null,
    "high_quality_base_model_ids": ["eleven_multilingual_v1"],
},

{
    "voice_id": "flq6f7yk4E4fJM5XTYuZ",
    "name": "Michael",
    "samples": null,
    "category": "premade",
    "fine_tuning": {
        "language": null,
        "is_allowed_to_fine_tune": false,
        "fine_tuning_requested": false,
        "finetuning_state": "not_started",
        "verification_attempts": null,
        "verification_failures": [],
        "verification_attempts_count": 0,
        "slice_ids": null,
        "manual_verification": null,
        "manual_verification_requested": false,
    },
    "labels": {
        "accent": "american",
        "age": "old",
        "gender": "male",
        "use case": "audiobook",
        "description ": "orotund",
    },
    "description": null,
    "preview_url": "https://storage.googleapis.com/eleven-public-prod/premade/voices/flq6f7yk4E4fJM5XTYuZ/c6431a82-f7d2-4905-b8a4-a631960633d6.mp3",
    "available_for_tiers": [],
    "settings": null,
    "sharing": null,
    "high_quality_base_model_ids": ["eleven_multilingual_v1"],
},
{
    "voice_id": "onwK4e9ZLuTAKqWW03F9",
    "name": "Daniel",
    "samples": null,
    "category": "premade",
    "fine_tuning": {
        "language": null,
        "is_allowed_to_fine_tune": false,
        "fine_tuning_requested": false,
        "finetuning_state": "not_started",
        "verification_attempts": null,
        "verification_failures": [],
        "verification_attempts_count": 0,
        "slice_ids": null,
        "manual_verification": null,
        "manual_verification_requested": false,
    },
    "labels": {
        "accent": "british",
        "description": "deep",
        "age": "middle aged",
        "gender": "male",
        "use case": "news presenter",
    },
    "description": null,
    "preview_url": "https://storage.googleapis.com/eleven-public-prod/premade/voices/onwK4e9ZLuTAKqWW03F9/7eee0236-1a72-4b86-b303-5dcadc007ba9.mp3",
    "available_for_tiers": [],
    "settings": null,
    "sharing": null,
    "high_quality_base_model_ids": ["eleven_multilingual_v1"],
},
